### ISSUE TITLE
support serverless-next.js ?

### ISSUE THREAD

**Issue by bonobozzzz** [newrelic/serverless-newrelic-lambda-layers#292]
hi.
Our project uses https://github.com/serverless-nextjs/serverless-next.js to deploy next.js application to lambda edge.
We are having trouble installing the apm agent because the newrelic documentation does not provide instructions on how to set it up when using serverless-next.js.
Does serverless-newrelic-lambda-layers support serverless-next.js? If so, how do I use it?

**Comment by mrickard** [comment]
@bonobozzzz Thank you for bringing this to our attention! I think that this New Relic plugin is unlikely to work for your use case. This plugin's primary purpose is to install and configure an instrumentation agent and extension via Lambda Layers, but your application requires Lambda@Edge, which [does not support Lambda Layers](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/edge-functions-restrictions.html). Among those restrictions are also restrictions on the use of environment variables. 

Despite those restrictions, you could instrument your application with New Relic, with a little manual work: 
1. Install `newrelic` in your application as a dependency, so that the NR Node agent is included in your deployment package.
2. Follow [the instructions](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy/#node) for wrapping a function manually...although you'll want to depart from those instructions this way:
3. Since you can't use environment variables, do not set `NEW_RELIC_NO_CONFIG_FILE` to `true`. Instead, define the app name, account id, and trusted account key in your project's `newrelic.js` configuration file (included with the agent), along with any other required environment variables. 
4. Without the use of Lambda Layers, you won't have the option of ingesting telemetry via the New Relic Lambda Extension, so you could set up a CloudWatch Log Subscription using the [Lambda CLI](https://github.com/newrelic/newrelic-lambda-cli)
