### ISSUE TITLE
Please add support for Go

### ISSUE THREAD

**Issue by msainty** [newrelic/serverless-newrelic-lambda-layers#334]
Hi,

You can use Golang as a language for Lambdas, this is a growing language and something we have started to experiment with and use as a languages for some services to get performance gains.

Please could you add Go as a language you support for your serverless plugin.

Many Thanks,

Mark

**Comment by mrickard** [comment]
@msainty This plugin is designed to get the latest New Relic Lambda Layer for the runtime. For Node, Python, and Java, that allows customers to instrument code without code changes. Go Lambda functions, since they're compiled, can't be instrumented without a code change. For Go, you'd want to instrument the function, and then ship the compiled function with the NR Go agent installed. 

What this plugin *could* do in that case is supply you with the Extension-only Lambda Layer, for shipping telemetry to NR, though you could get the same functionality without the plugin--you'd just need to install the Extension only layer and add some environment variables. Is that something like the functionality you're thinking of?
